use_frameworks!

platform :ios, '9.0'

target 'MKLoRaWAN-B_Example' do
  pod 'MKLoRaWAN-B', :path => '../'

  target 'MKLoRaWAN-B_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
